### ISSUE TITLE
Stop on known best tour found

### ISSUE THREAD

**Issue by jakobbossek** [wiomax/MAOS-TSP#1]
Hello,

is it possible to provide the length of the shortest tour as another stopping criterion and deactivate all the other conditions? We need that at the moment for a fair comparisson of MAOS with some other TSP-algorithms.

Regards,

Jakob

**Comment by wiomax** [comment]
Hi Jakob,

Please put your optimal tour at the directory: myprojects/tasks/TSP/solution, and the naming scheme is: [Instance Name].opt.tour for each instance. 

The usage will be updated on: http://www.wiomax.com/MAOS-TSP/

Please let us know if you have any question. Thanks.

**Comment by jakobbossek** [comment]
Hi,

thanks for that. This helps definitely :+1:
By the way. The solver seems to be pretty well written, but it lacks in-code documentation (javadoc).
It is pretty hard to dive in the code structure though ;-)

One more question: beside T, TCon and DUP_TIMES there are no more hidden termiation conditions I guess. How to deactivate all of them? Simply by setting a very high value?

Regards,

Jakob

**Comment by jakobbossek** [comment]
Well, MAOS needs us to provide a TOUR file with the actual optimal tour, but we have only the lengths of the optimal tours for our tests set, but not the tour itself. Could you please offer a possibility to pass only the length of the optimal tour as an optional stopping criterion?

**Comment by wiomax** [comment]
A new parameter "opt=[value]" is added for your requirement.

**Comment by jakobbossek** [comment]
Thanks a lot. As a last step: Could you give me some advise on how to build a jar file of the source or maybe would you be so kind to update the jar file in the binary folder?

Thanks in advance!

**Comment by wiomax** [comment]
The binary folder is updated now.

**Comment by jakobbossek** [comment]
Thank you very much. I think we can close this now.
